name: Auto Update Financial Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必須確保機器人有寫入權限
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install yfinance pandas pandas_datareader requests
      - name: Run script
        run: python update_data.py
      - name: Push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add historical_data.csv
          git commit -m "Auto update $(date)" || exit 0
          git push
